In [38]:
import pickle
import pandas as pd
import scipy
import numpy as np
import sklearn
import random
from sklearn.metrics.pairwise import cosine_similarity
import os, sys
import importlib

In [39]:
parentdir = 'C:\\Users\\danie\\Documents\\work\\testingRS\\TESTS'
sys.path.insert(0,parentdir) 
importlib.reload(entity)
from entity import User, CB, MF

In [30]:
with open('C:\\Users\\danie\\Documents\\work\\testingRS\\TESTS\\objects\\tfidf.pkl', 'rb') as f:
    tfidf_matrix, tfidf_feature_names, full_item_ids = pickle.load(f)

with open('C:\\Users\\danie\\Documents\\work\\testingRS\\TESTS\\objects\\subset_1000.pkl', 'rb') as f:
    utility_matrix_1, interactions_work_1 = pickle.load(f)

In [40]:
USER = '-3596626804281480007'
user_object = User(USER, utility_matrix_1, interactions_work_1)
cb = CB(user_object)
results_CB = cb.compute_similarities(cb.user.interactions_df,cb.user.id, full_item_ids, tfidf_matrix, cb.user.items_to_ignore)

In [41]:
results_CB

,-2081760549863309770,-2176468683077766369,-3173020603774823976,-3367778232969996503,-4110991218639855802,-4186591400427142356,-4374331682165863764,-454649054276160610,-4760639635023250284,-4994468824009200256,...,-2778760500673113802,1003778007373126185,6652210819857467321,-4110354420726924665,5619251370090681244,84318068629167514,3703141283586666995,-7101541512657907485,3067875254349597654,7767869406844505704
-3596626804281480007,0.048819,0.367331,0.076986,0.173454,0.118737,0.067395,0.114469,0.08325,0.216915,0.096144,...,0.07315,0.077565,0.110094,0.083722,0.178852,0.009385,0.046247,0.064871,0.137906,0.096121

In [22]:
FACTORS_MF = 15
USER = '-3596626804281480007'
user_object = User(USER, utility_matrix_1, interactions_work_1)
mf = MF(user_object)
mf_predctions = mf.predict_matrix(mf.user.utility_matrix, FACTORS_MF)
results_MF = mf.remove_items(FACTORS_MF)

C:\Users\danie\Documents\work\testingRS\TESTS\entity.py:77: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  users_items_pivot_matrix = utility_matrix.as_matrix()

In [25]:
results_MF

contentId,-1021685224930603833,-1591454024897803197,-1672166631728511207,-1802980374508081539,-2081760549863309770,-2176468683077766369,-2271868873349907631,-2711301039947937868,-2778760500673113802,-2826566343807132236,...,8095004770374551394,809601605585939618,8194079557551008273,8219310215587599928,8298709454703868984,84318068629167514,8471417198703153120,8545647269051113523,8565115980515859979,9032993320407723266
-3596626804281480007,0.115669,0.158806,0.205226,0.182964,0.168654,0.256359,0.153038,0.189915,0.136501,0.159022,...,0.133869,0.12363,0.123409,0.170801,0.160013,0.158638,0.178037,0.170801,0.136486,0.172972

In [43]:
results_MF.append(results_CB, sort=True) ##el primero es MF

,-1021685224930603833,-1591454024897803197,-1672166631728511207,-1802980374508081539,-2081760549863309770,-2176468683077766369,-2271868873349907631,-2711301039947937868,-2778760500673113802,-2826566343807132236,...,8095004770374551394,809601605585939618,8194079557551008273,8219310215587599928,8298709454703868984,84318068629167514,8471417198703153120,8545647269051113523,8565115980515859979,9032993320407723266
-3596626804281480007,0.115669,0.158806,0.205226,0.182964,0.168654,0.256359,0.153038,0.189915,0.136501,0.159022,...,0.133869,0.123630,0.123409,0.170801,0.160013,0.158638,0.178037,0.170801,0.136486,0.172972
-3596626804281480007,0.010515,0.128308,0.020962,0.121353,0.048819,0.367331,0.144854,0.050575,0.073150,0.089152,...,0.170196,0.058101,0.123156,0.124496,0.129474,0.009385,0.143339,0.083885,0.071487,0.086540

contentId,-1021685224930603833,-1591454024897803197,-1672166631728511207,-1802980374508081539,-2081760549863309770,-2176468683077766369,-2271868873349907631,-2711301039947937868,-2778760500673113802,-2826566343807132236,...,8095004770374551394,809601605585939618,8194079557551008273,8219310215587599928,8298709454703868984,84318068629167514,8471417198703153120,8545647269051113523,8565115980515859979,9032993320407723266
-3596626804281480007,0.115669,0.158806,0.205226,0.182964,0.168654,0.256359,0.153038,0.189915,0.136501,0.159022,...,0.133869,0.12363,0.123409,0.170801,0.160013,0.158638,0.178037,0.170801,0.136486,0.172972

In [266]:
# topn = 10
# similar_indices = np.argsort(-cosine_similarities[0,:])[0:topn]
# similar_items = [(items_to_compare[i], cosine_similarities[0,i]) for i in similar_indices]
# similar_items

In [ ]:
users = interactions_work_1.personId.unique()